# Generated by Django 5.2 on 2025-04-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="latest_price",
        ),
        migrations.RemoveField(
            model_name="stockprice",
            name="turnover",
        ),
    ]
